baseURL = "https://seokbeomKim.github.io/"
languageCode = "en-us"
title = "코드몽키의 개발 일지"
theme = "pickles"
paginate = 5

[params]
	subtitle = "일상 속 글쓰는 공간"

	# Socal accounts
	github = "seokbeomKim"
	linkedin = "sukbeomkim"
	disqus = "beomiyi-beulrogeu"

	# plugin supports
	mathjax = true

	# my custom css fils
	custom_css = ["css/img.css"]

[[menu.main]]
	name = "블로그"
	url = "/"
	weight = 1

[[menu.main]]
	name = "태그"
	url = "/tags"
	weight = 2

[[menu.main]]
	name = "카테고리"
	url = "/categories"
	weight = 3

[[menu.main]]
	name = "소개"
	url = "/about"


[markup]
	defaultMarkdownHandler = "goldmark"

	[markup.tableOfContents]
		startLevel = 1
		endLevel = 3
		ordered = true

[taxonomies]
	category = "categories"
	tags = "tags"
