baseURL = "https://seokbeomKim.github.io/"
languageCode = "en-us"
title = "A Developer's Note"
theme = "pickles"
paginate = 5

[params]
	subtitle = "Technical Writing in Daily Life"

	# Socal accounts
	github = "seokbeomKim"
	linkedin = "sukbeomkim"
	disqus = "beomiyi-beulrogeu"

	# plugin supports
	mathjax = true

	# my custom css fils
	custom_css = ["css/img.css"]

[[menu.main]]
	name = "Blog"
	url = "/"
	weight = 1

[[menu.main]]
	name = "Tags"
	url = "/tags"
	weight = 2

[[menu.main]]
	name = "Categories"
	url = "/categories"
	weight = 3

[[menu.main]]
	name = "About"
	url = "/about"


[markup]
	defaultMarkdownHandler = "goldmark"

	[markup.tableOfContents]
		startLevel = 1
		endLevel = 3
		ordered = true 

[taxonomies]
	category = "categories"
	tags = "tags"
