baseURL: /
languageCode: en-us
title: 평범한 개발자
defaultContentLanguage: en
buildDrafts: false
buildFuture: false

menu:
  main:
    - name: "Main"
      url: /
      weight: 1
    - name: "Tags"
      url: /tags
      weight: 2
    - name: "About"
      url: /about
      weight: 3

markup:
  highlight:
    anchorLineNos: true
    codeFences: true
    guessSyntax: false
    tabWidth: 4
    lineNumbersInTable: false
    noClasses: false
    lineNos: true
    style: emacs
  goldmark:
    extensions:
      footnote: true
      linkify: true
      linkifyProtocol: https
      table: true
    renderer:
      unsafe: true

hasCJKLanguage: true
permalinks:
  posts: /posts/:title/

googleAnalytics: G-Y7VW74D2P3
disqusShortname: seokbeomkim-github-io

# Site parameters
params:
  # Site Author
  author: "김석범 (Sukbeom Kim)"
  description: "Jason Kim"
  enableGitInfo: true

  ###########################################
  # Optional Configuration
  ###########################################

  # To enable RSS, you could set `enableRSS: true`, default is `true`
  enableRSS: true
  # To enable comments, you may need to set `disqusShortname`
  enableComments: false
  # To enable comments, you may need to set `googleAnalytics`
  enableGoogleAnalytics: false
  # To enable table of content, you could set `showToc: true`, default is `false`
  showToc: true
  # To hidden powerBy message in the page footer, you could set: `showPowerBy: false`, default is `true`
  showPowerBy: false
  # To enable math typesetting , you could set `math: true`, default is `false`
  math: true
  # To hidden post summary in home page, you could set `hiddenPostSummaryInHomePage: true`, default is `false`
  hiddenPostSummaryInHomePage: false
  # Website copy write, default: '© Copyright 2021 ❤️ {params.author}'
  copyright: "Copyright - Sukbeom Kim"

  notitle: true # hide title
  next: true
  nomenu: true

  # Extra links in navigation
  links:
    ## e.g.
    # - name: Project
    #   path: /project

  # You can put your custom css and js to `static` directory, or use remote css and js files which start with `http://` or `https://`
  customCSS:
    - css/img.css
    - css/noto_sans_kr.css
    - css/nanumgothic.css
    - css/syntax.css
    ## e.g.
    # - css/custom.css # local css in `static/css/custom.css`
    # - https://example.com/custom.css # remote css
  customJS:
    ## e.g.
    # - js/custom.js # local js in `static/js/custom.js`
    # - https://example.com/custom.js # remote js

module:
  imports:
    - path: github.com/barklan/hugo-dead-simple
